### ISSUE TITLE
目前我遇到的问题：

### ISSUE THREAD

**Issue by AGmouse** [MakesYT/NchargeL#1]
1.  移动的网络可能存在连接问题，我用移动的网络裸连启动器会有连接错误的提示。
![启动客户端问题](https://user-images.githubusercontent.com/102458989/160272413-a599054a-6b34-470c-991e-5f5971c7e434.jpg)

2. 启动器在显示用户登录信息过期并且重新登陆后有几率报错，目前没有截图。
3. 偶尔出现客户端正常登陆但是游戏无法正常启动的问题。显示为启动游戏，但是实际并没有正常启动。
![无法正常启动](https://user-images.githubusercontent.com/102458989/160272637-4bfd983f-e1fd-4db5-b913-9948597208dc.jpg)

**Comment by AGmouse** [comment]
对问题3的补充：客户端正常启动，但是点击启动游戏并且有弹窗提示等待游戏窗口时无法正常启动游戏。并会在一段时间后显示客户端已经退出并且右上角的启动游戏开始无限读条。

**Comment by Maklith** [comment]
az你这不分开我很难搞

**Comment by AGmouse** [comment]
有新问题我一定分开写

**Comment by AGmouse** [comment]
改过了，问题4去服务器问题那边了

**Comment by Maklith** [comment]
bug3已修复,1和2为HTTP请求问题,原因网络不稳定,没有什么好的解决办法
